AutoRia/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Data.Entities;
using Data.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using AutoMapper;
using Core.Dtos;
using Microsoft.AspNetCore.Authorization;
using AutoRia.SeedExtensions;
using Core.Interfaces;

namespace AutoRia.Controllers
{
    [Authorize(Roles = Roles.ADMIN)]
    public class CarsController : Controller
    {
        private readonly IMapper mapper;
        private readonly CarsDbContext ctx;
        private readonly IFilesService filesService;

        public CarsController(IMapper mapper, CarsDbContext ctx, IFilesService filesService)
        {
            this.mapper = mapper;
            this.ctx = ctx;
            this.filesService = filesService;
        }

        // -+-+-+-+-+-+-+-+-+-+-+-+- INDEX -+-+-+-+-+-+-+-+-+-+-+-+-
        public IActionResult Index()
        {
            var cars = ctx.Cars
                .Include(x => x.Category)
                .Include(x => x.FuelType)
                .Where(x => !x.Archived)
                .ToList();
            return View(mapper.Map<List<CarDto>>(cars));
        }

        // -+-+-+-+-+-+-+-+-+-+-+-+- ARCHIVE -+-+-+-+-+-+-+-+-+-+-+-+-
        public IActionResult Archive()
        {
            // .. load data from database ..
            var cars = ctx.Cars
                .Include(x => x.Category) // LEFT JOIN
                .Where(x => x.Archived)
                .ToList();
            return View(mapper.Map<List<CarDto>>(cars));
            
        }

        public IActionResult ArchiveItem(int id)
        {
            var cars = ctx.Cars.Find(id);

            if (cars == null) return NotFound();

            cars.Archived = true;
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        // -+-+-+-+-+-+-+-+-+-+-+-+- DELETE -+-+-+-+-+-+-+-+-+-+-+-+-
        public async Task<IActionResult> Delete(int id)
        {
            var car = ctx.Cars.Find(id);

            if (car == null) return NotFound();

            //delete image
            if (car.ImageUrl != null)
                await filesService.DeleteCarImage(car.ImageUrl);

            ctx.Cars.Remove(car);
            ctx.SaveChanges();

            return RedirectToAction("Archive");
        }

        // -+-+-+-+-+-+-+-+-+-+-+-+- RESTORE FROM ARCHIEVE -+-+-+-+-+-+-+-+-+-+-+-+-
        public IActionResult RestoreItem(int id)
        {
            var car = ctx.Cars.Find(id);

            if (car == null) return NotFound();

            car.Archived = false;
            ctx.SaveChanges();

            return RedirectToAction("Archive");
        }

        // -+-+-+-+-+-+-+-+-+-+-+-+- CREATE -+-+-+-+-+-+-+-+-+-+-+-+-
        [HttpGet]
        public IActionResult Create()
        {
            LoadTypesOfFuel();
            LoadCategories();
            ViewBag.CreateMode = true;
            return View("Upsert");
        }

        [HttpPost]
        public async Task<IActionResult> Create(CarDto car)
        {
            // TODO: add data validation
            if (!ModelState.IsValid)
            {
                ViewBag.CreateMode = true;
                LoadTypesOfFuel();
                LoadCategories();
                return View("Upsert", car);
            }

            var entity = mapper.Map<Car>(car);

            entity.ImageUrl = await filesService.SaveCarImage(car.Image);

            ctx.Cars.Add(entity);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        // -+-+-+-+-+-+-+-+-+-+-+-+- EDIT -+-+-+-+-+-+-+-+-+-+-+-+-
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var car = ctx.Cars.Find(id);

            if (car == null) return NotFound();

            LoadTypesOfFuel();
            LoadCategories();
            ViewBag.CreateMode = false;
            return View("Upsert", mapper.Map<CarDto>(car));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CarDto car)
        {
            // TODO: add data validation
            if (!ModelState.IsValid)
            {
                ViewBag.CreateMode = true;
                LoadTypesOfFuel();
                LoadCategories();
                return View("Upsert", car);
            }

            if (car.Image != null)
            {
                car.ImageUrl = await filesService.EditCarImage(car.ImageUrl, car.Image);
            }

            ctx.Cars.Update(mapper.Map<Car>(car));
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        // -+-+-+-+-+-+-+-+-+-+-+-+- DEATILS -+-+-+-+-+-+-+-+-+-+-+-+-
        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var product = ctx.Cars.Find(id);

            if (product == null) return NotFound();

            return View(mapper.Map<CarDto>(product));
        }

        // -+-+-+-+-+-+-+-+-+-+-+-+- FUNCTIONS -+-+-+-+-+-+-+-+-+-+-+-+-
        private void LoadCategories()
        {
            // ViewBag.PropertyName = value;
            ViewBag.Categories = new SelectList(ctx.Category.ToList(), "Id", "Name");
        }
        private void LoadTypesOfFuel()
        {
            // ViewBag.PropertyName = value;
            ViewBag.FuelTypes = new SelectList(ctx.FuelType.ToList(), "Id", "Name");
        }
    }
}

AutoRia/Controllers/CartController.cs
using AutoMapper;
using AutoRia.Extensions;
using Core.Dtos;
using Data.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AutoRia.Services;
using Microsoft.EntityFrameworkCore;
using Core.Interfaces;
using Microsoft.AspNetCore.Identity;

namespace AutoRia.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService cartService;
        private readonly RoleManager<IdentityRole> userManager;

        public CartController(ICartService cartService)
        {
             this.cartService = cartService;
             this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(cartService.GetCars());
        }

        public IActionResult Add(int id, string? returnUrl)
        {
            cartService.AddItem(id);
            return Redirect(returnUrl ?? "/");
        }

        public IActionResult Remove(int id)
        {
            cartService.RemoveItem(id);
            return RedirectToAction("Index");
        }
    }
}

AutoRia/Controllers/RequestsController.cs
using AutoMapper;
using Core.Interfaces;
using Core.Dtos;
using Data.Data;
using Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AutoRia.Controllers
{
    [Authorize]
    public class RequestsController : Controller
    {
        private readonly IRequestService requestService;
        private string UserId => User.FindFirstValue(ClaimTypes.NameIdentifier)!;
        private string UserEmail => User.FindFirstValue(ClaimTypes.Email)!;

        public RequestsController(IRequestService requestService)
        {
            
            this.requestService = requestService;
        }

        public IActionResult Index()
        {
            return View(requestService.GetRequests(UserId));
        }
        public IActionResult Create()
        {
            // create request
            requestService.Create(UserId, UserEmail);

            return RedirectToAction(nameof(Index));
        }
    }
}

AutoRia/Views/Shared/_CarHomeCardPartial.cshtml
@model Car

<div class="col">
    <div class="card h-100">
        <img height="130" src="@(Model.ImageUrl ?? "https://thumbs.dreamstime.com/b/no-image-icon-vector-available-picture-symbol-isolated-white-background-suitable-user-interface-element-205805243.jpg")" class="card-img-top" alt="@Model.Mark">
        <div class="card-body">
            <h5 class="card-title">
                <a asp-controller="Cars" asp-action="Details" asp-route-id="@Model.Id">@Model.Mark @Model.Model</a>
            </h5>
            <p class="card-text">
                Year: @Model.Year<br/>
                Year: @Model.Year<br/>
                Mileage: @Model.Mileage
            </p>
            <a asp-controller="Cart" asp-action="Add" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.Path" class="btn btn-primary">Add to Favourite</a>
        </div>
        <div class="card-footer">
            <small class="text-muted">
                Price: <span class="badge bg-success">@Model.Price$</span>
            </small>
        </div>
    </div>
</div>

AutoRia/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject ICartService cartService;
@inject SignInManager<User> SignInManager
@using AutoRia.SeedExtensions;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarDeluxe</title>
    <link rel="shortcut icon" href="https://deluxerentalcars.ch/wp-content/uploads/2018/07/logo_dlrc_new.png" type="image/png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutoRia.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://deluxerentalcars.ch/wp-content/uploads/2018/07/logo_dlrc_new.png" alt="Alternate Text" width="100px" /></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            
                            @if (User.IsInRole(Roles.ADMIN))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Catalog</a>
                                </li>
                            }
                            @* @if(SignInManager.IsSignedIn(User)) *@
                            @* { *@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Requests" asp-action="Index">Orders</a>
                            </li>
                            @* } *@
                        </ul>
                        </ul>
                        <ul class="navbar-nav">
                            <partial name="_LoginPartial.cshtml" />
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                                    <i class="bi bi-bookmark-heart"></i>
                                    Cart (@cartService.GetCount())
                                    </a>
                            </li>
                        </ul>
                    </div>
                    <div class="justify-content-right">
                        <button class="btn btn-danger me-2" type="button"><i class="bi bi-bag-fill"></i> Sell The Car</button>
                    </div>
                </div>
            </nav>
        </div>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <img src="https://deluxerentalcars.ch/wp-content/uploads/2018/07/logo_dlrc_new.png" alt="Alternate Text" width="100px"/>&copy; 2024 - CarDeluxe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>